### ISSUE TITLE
Building from source creates unusable .desktop file when grep 2.23 is installed.

### ISSUE THREAD

**Issue by rapgro** [lxde/lximage-qt#50]
Please use the cmake module directly from liblxqt and unbundle it. We suffer in Fedora from a bug with newer grep.
See https://github.com/lxde/lxqt/issues/957

**Comment by palinek** [comment]
I've submitted PR for this... but I don't know if others wish the liblxqt dependency...

**Comment by rapgro** [comment]
Thanks. :+1:

**Comment by agaida** [comment]
See lxde/lxqt#957
@palinek @PCMan @paulolieuthier @jleclanche 
unfixed: compton-conf, libfm-qt, lximage-qt, obconf-qt and pcmanfm-qt
we should discuss it on the list if you agree - i see right now no downsides in a build-dependency, the resulting packages do not depend on liblxqt, because the pure cmake mechanics are used only at build time. Until we decide this we should push the '-a' thing into the packages.

**Comment by agaida** [comment]
@all - the github bug tracking is horrible, we should really consider to use track or redmine for this

**Comment by luis-pereira** [comment]
@agaida IIRC @PCMan pushed for not having an liblxqt compile dependency.

**Comment by agaida** [comment]
i'm fine with that too - but in that case we should build our own pkg-lxqt-tools with some arch indipendend scripts in it. In other words.  a script is a script is a script - and if the scripting is indipendend enought it should be no problem to put it in a separated packages/repo and avoid code dupes

**Comment by rapgro** [comment]
+1 for the independent scripts

**Comment by agaida** [comment]
@rapgro - i would not place build scripts in common. i would really pack them into a separated repo and make a package out of them. Hey - it's github, we don't have to pay per repository. Joke aside, its a lot easier to distribute if the scripts would be in a single package. A package with some internal used scripts is fast uploaded in case of changes and don't affect any users in case of changes.
